version: "3.8"
services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    command: npm run develop -- -H 0.0.0.0
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules
    ports:
      - "8000:8000"

volumes:
  node_modules:
